
let emojis = [
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },
    { hex: '&#x1F61B;', title: 'face with tongue', subGroup: 'face tongue', majorGroup: 'Smileys & Emotion' },

]


module.exports = {
    getEmojis(req, res) {
        res.send(emojis)
    }
}